### ISSUE TITLE
how can I map output of hand_pose_model and body_pose_model together?

### ISSUE THREAD

**Issue by init-22** [Hzzone/pytorch-openpose#28]
Hello, I am trying to check wheather a finger keypoint is above the shoulder keypoint, how can I map a particual shoulder keypoint to the exact finger keypoint for this?

**Comment by ChibiChibz** [comment]
Hey @IsaacPatole ! It's not implemented, but I think there is a way to workaround it. The way this code works is that it will check if shoulders, elbow and wrist of a certain arm are estimated and then starts the hand detection and estimation. And I think it always starts looking for left arm first so maybe it helps you to connect the drawn hands and the body keypoints.
