### ISSUE TITLE
Is this available for commercial work?

### ISSUE THREAD

**Issue by kartikeyporwal** [Hzzone/pytorch-openpose#30]
Hi, Appreciations for such a nice work!!

I was looking this project and noticed that you didn't add any license to this project. I want to know whether this can be used for commercial projects or not.

I searched in official [Openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) and found out that they don't offer commercial license for free.

Since your project is a derivative of their work, so it's owned by CMU based on the [license of openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/e086e6fc6a5f4650d5c3a100b8ced8363fd2d099/LICENSE#L20). Could you look [this issue](https://github.com/CMU-Perceptual-Computing-Lab/openpose/pull/321) from [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose/)  repo for more detail?

Also, we can't use their pretrained model which follows the same license as their code, [this](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1444) is the issue, I'm referring to. Since you converted their Caffe model to PyTorch model, it's kind of derivative of their work only and as per their license, your work is CMU's work if used commercially and CMU's Openpose license apply by default.

So, this or any other implementation of Openpose can't be used commercially!

What do you think about this?

**Comment by Hzzone** [comment]
I have no idea about your problem. However, I am sure that you should apply for the commercial license from CMU-Perceptual-Computing-Lab.

**Comment by kartikeyporwal** [comment]
Hi, Thanks for reply. I'm not referring to my problem only, I wanted to know your view in this as a project owner, do you think your implementation can be used commercially?

**Comment by Hzzone** [comment]
No.
