### ISSUE TITLE
ZeroDivisionError: float division by zero in body.py

### ISSUE THREAD

**Issue by hankroldd** [Hzzone/pytorch-openpose#42]
Thanks for your great work!

**When I run the demo.py with a change of  test_image = 'images/090932040.jpg', there is an error :**

```
body.py:123: RuntimeWarning: invalid value encountered in true_divide
  vec = np.divide(vec, norm)
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    candidate, subset = body_estimation(oriImg)
  File "src\body.py", line 135, in __call__
    0.5 * oriImg.shape[0] / norm - 1, 0)
ZeroDivisionError: float division by zero
```
![090932040](https://user-images.githubusercontent.com/52962491/102709541-b0241c80-42e6-11eb-835f-4a76308d1328.jpg)

**This is the image I used. Could you help me with the error?**

**Comment by PatrickChoDev** [comment]
How did you fix this issue?

**Comment by Adeel-Intizar** [comment]
@hankroldd I am having same issue, can you kindly tell how did you solve it?
Thank you

**Comment by Adeel-Intizar** [comment]
I managed to solve it, in case if anyone is looking for it, just add 1e-6 to the norm variable which is causing this error and the problem will be solved
