### ISSUE TITLE
Might be an error?

### ISSUE THREAD

**Issue by Sawyer-Wu** [Hzzone/pytorch-openpose#62]
I found that the last element of 'no_relu_layers' defined in model.bodypose_model is 'Mconv7_stage6_L1'. Is it should be 'Mconv7_stage6_L2'?
![{EE0F82F8-5943-47CA-B9DB-8C66FD05C13D}](https://user-images.githubusercontent.com/56818898/129828315-da050209-a9bb-4bc9-8c6c-3ed02ac5af95.png)

**Comment by Hzzone** [comment]
I have checked it. You are right. Did you run them to check whether there are any differences?

**Comment by Sawyer-Wu** [comment]
> I have checked it. You are right. Did you run them to check whether there are any differences?

I ran demo.py on one image. There seems to be no difference. But I'm not very sure about that.

**Comment by Hzzone** [comment]
Thanks a lot, maybe the small negative value would not have many influences on the final results.

**Comment by Sawyer-Wu** [comment]
> Thanks a lot, maybe the small negative value would not have many influences on the final results.

😁
