### ISSUE TITLE
how to generate the graph like this?

### ISSUE THREAD

**Issue by shu0x0y** [Hzzone/pytorch-openpose#78]
@Hzzone Hello sir, the figure on the left is obtained body.py run, I wonder if this code can generate the graph on the right, if so, can you tell me the method?

![image](https://user-images.githubusercontent.com/96320419/217190228-92f72bd2-591a-438a-8bf9-ce76715f0d8a.png)

**Comment by Hzzone** [comment]
See https://github.com/Hzzone/pytorch-openpose/blob/5ee71dc10020403dc3def2bb68f9b77c40337ae2/src/body.py#L216
change to
```python
 canvas = util.draw_bodypose(np.zeros_like(oriImg), candidate, subset) 
```

**Comment by shu0x0y** [comment]
> See
> 
> https://github.com/Hzzone/pytorch-openpose/blob/5ee71dc10020403dc3def2bb68f9b77c40337ae2/src/body.py#L216
> 
> 
> change to
> ```python
>  canvas = util.draw_bodypose(np.zeros_like(oriImg), candidate, subset) 
> ```

OK, I get it, Thank you very much, it will help me much!
