### ISSUE TITLE
3D real-time single-person keypoint detection using 3D triangulation from multiple single views

### ISSUE THREAD

**Issue by JeremyKeusters** [Hzzone/pytorch-openpose#9]
I'm especially interested in the 3D real-time single-person keypoint detection using 3D triangulation which is available in the original OpenPose Caffe. I read in the README that you used [caffemodel2pytorch](https://github.com/vadimkantorov/caffemodel2pytorch) for converting this code from Caffe. Could you maybe give some more details on this? So I could also convert the 3D triangulation code from the original repo?

Thanks in advance!

**Comment by Hzzone** [comment]
Model weights conversion has nothing to do with 3D triangulation. Firstly model inferences images from multi-veiw, and then does 3D triangulation according to detected keypoints.

**Comment by JeremyKeusters** [comment]
You're completely right, I'm sorry. Implemented it myself, thanks.
